### PR TITLE
Use request context instead of context.Background()

### PR DESCRIPTION
**Pull request by amenzhinsky**

### CODE REVIEW

**Comment by deniszh** [comment]
Travis says that will not gonna work. Also some commentary why do you want to do this will be nice too.

**Comment by amenzhinsky** [comment]
@deniszh I'm sorry, I forgot to delete unused import.

So this PR makes stopping http server more consistent because when you stop it all request context are cancelled as well. 

At the same time we're working on the autorization feature for carbonapi and it would be nice to use request contexts since we use handler wrappers like `authUser(renderHandler)`.

Thanks.

**Comment by amenzhinsky** [comment]
CI build is failing, do you have any idea why?

**Comment by Civil** [comment]
Seems to be a bug in build script, it shouldn't try to build packages for PR requests.

**Comment by deniszh** [comment]
Upload to packagecloud is broken. Not sure that we should do that on every Travis run, though.
@Civil ?

**Pull request merged**
