### PR TITLE
Added support of aliasByPostgre function

### PR DESCRIPTION
**Pull request by RudW0lf**
This function allow to resolve some graphite path domains to human-readable format.

### CODE REVIEW

**Comment by arodland** [comment]
Please no "Postgre". The name of the database is Postgres or PostgreSQL, not Postgre.

**Comment by Civil** [comment]
Vendoring part is still missing. And a good point by @arodland

**Comment by Civil** [comment]
JFIY: You've never updated vendored deps, so I can't merge that PR.

**Comment by RudW0lf** [comment]
@Civil Do I need additional changes?

**Pull request merged**
