### PR TITLE
Metrics refactor

### PR DESCRIPTION
**Pull request by msaf1980**

### CODE REVIEW

**Comment by Civil** [comment]
@carrieedwards I think you might also have some input on this proposal to refactor metrics reported by carbonapi.

I would copy (and translate) message from Michail about that PR:
Translation (not word to word, but I've tried to pass the meaning, @msaf1980  correct me if I'm wrong):
I've drafted my vision on an evolution of metrics reported by carbonapi. As a Pro of this approach: high degree of compatibility with current metrics (with exception of metrics reported by goruntime, they are moved out to `runtime` sub-branch, but that can be changed), ability to create your own custom buckets with custom names and ability to apply summaries and histograms. It would be also possible to implement something similar in carbon-clickhouse/graphite-clickhouse. For some metrics, StatsD is used but it's possible to do everything on carbonapi side.

Original:
```
Набросал тут свое видение дальнейшего развития метрик в carbonapi. К плюсам можно отнести достаточно высокую совместимость с текущими метриками (за исключением метрик  гошного рантайма - они вынесены в подветку runtime, но можно и поменять), возможность сделать свои бакеты с кастомными именами, применить "суммирующие" гистограммы. В принципе, подобное решение можно будет завести и в carbon-clickhouse/graphite-clickhouse. Для некотрых метрик используется StatsD (но можно конечно делать обработку на стороне carbonapi)
```

**Comment by msaf1980** [comment]
Also deprecate carbonzipper is planned.

**Comment by Civil** [comment]
Yeah, I don't think cmd/carbonzipper is maintained or used by anyone. It's not packaged since forever, there were almost no code changes in last several years on that side as well.

**Comment by carrieedwards** [comment]
> @carrieedwards I think you might also have some input on this proposal to refactor metrics reported by carbonapi.
> 
> I would copy (and translate) message from Michail about that PR: Translation (not word to word, but I've tried to pass the meaning, @msaf1980 correct me if I'm wrong): I've drafted my vision on an evolution of metrics reported by carbonapi. As a Pro of this approach: high degree of compatibility with current metrics (with exception of metrics reported by goruntime, they are moved out to `runtime` sub-branch, but that can be changed), ability to create your own custom buckets with custom names and ability to apply summaries and histograms. It would be also possible to implement something similar in carbon-clickhouse/graphite-clickhouse. For some metrics, StatsD is used but it's possible to do everything on carbonapi side.
> 
> Original:
> 
> ```
> Набросал тут свое видение дальнейшего развития метрик в carbonapi. К плюсам можно отнести достаточно высокую совместимость с текущими метриками (за исключением метрик  гошного рантайма - они вынесены в подветку runtime, но можно и поменять), возможность сделать свои бакеты с кастомными именами, применить "суммирующие" гистограммы. В принципе, подобное решение можно будет завести и в carbon-clickhouse/graphite-clickhouse. Для некотрых метрик используется StatsD (но можно конечно делать обработку на стороне carbonapi)
> ```

Hi. We currently aren't using the cmd functionality at this time, as we are just using the expr package. But I took a look at the changes and they look fine to me.

**Review by Civil — APPROVED** [review]

**Pull request merged**
